services:
  db:
    image: pgvector/pgvector:pg16
    container_name: mepreparo_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mepreparo_pass
      POSTGRES_DB: mepreparo
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
