// Banco SEMILLA — mínimo para construir y probar el motor adaptativo.
// NO pretende cobertura curricular: Gema generará el banco grande desde el RAG
// (ver docs/PLAN-banco-preguntas.md) cumpliendo el mismo tipo `Pregunta`.
// Preguntas orientadas a 5° básico como referencia de prueba.

import type { BancoPreguntas } from "./tipos";

export const BANCO_SEMILLA: BancoPreguntas = [
  // ---------------- MATEMÁTICA ----------------
  {
    id: "mat_seed_1",
    materia: "matematica",
    curso: "5basico",
    dificultad: 1,
    tema: "numeros",
    enunciado: "¿Cuánto es 6 × 7?",
    opciones: ["42", "36", "48", "13"],
    correcta: 0,
  },
  {
    id: "mat_seed_2",
    materia: "matematica",
    curso: "5basico",
    dificultad: 2,
    tema: "numeros",
    enunciado: "¿Cuál es el valor de la cifra 4 en el número 3.482?",
    opciones: ["4 unidades", "4 decenas", "4 centenas", "4 unidades de mil"],
    correcta: 2,
  },
  {
    id: "mat_seed_3",
    materia: "matematica",
    curso: "5basico",
    dificultad: 3,
    tema: "fracciones",
    enunciado: "Sofía comió 3 de las 8 porciones de una pizza. ¿Qué fracción comió?",
    opciones: ["3/8", "8/3", "3/5", "5/8"],
    correcta: 0,
  },
  {
    id: "mat_seed_4",
    materia: "matematica",
    curso: "5basico",
    dificultad: 4,
    tema: "fracciones",
    enunciado: "¿Cuánto es 1/4 + 2/4?",
    opciones: ["3/4", "3/8", "2/8", "1/2"],
    correcta: 0,
  },
  {
    id: "mat_seed_5",
    materia: "matematica",
    curso: "5basico",
    dificultad: 5,
    tema: "proporcionalidad",
    enunciado:
      "Si 2 kg de pan cuestan $2.400, ¿cuánto cuestan 5 kg al mismo precio?",
    opciones: ["$6.000", "$4.800", "$5.400", "$12.000"],
    correcta: 0,
  },

  // ---------------- LENGUAJE ----------------
  {
    id: "len_seed_1",
    materia: "lenguaje",
    curso: "5basico",
    dificultad: 1,
    tema: "vocabulario",
    enunciado: "¿Cuál palabra es un sustantivo?",
    opciones: ["correr", "casa", "rápido", "y"],
    correcta: 1,
  },
  {
    id: "len_seed_2",
    materia: "lenguaje",
    curso: "5basico",
    dificultad: 2,
    tema: "ortografia",
    enunciado: "¿Cuál palabra está bien escrita?",
    opciones: ["aver", "haber", "a ver", "haver"],
    correcta: 1,
  },
  {
    id: "len_seed_3",
    materia: "lenguaje",
    curso: "5basico",
    dificultad: 3,
    tema: "comprension_lectora",
    enunciado:
      "«El perro movía la cola sin parar al ver a su dueño.» ¿Cómo se sentía el perro?",
    opciones: ["Asustado", "Contento", "Enojado", "Cansado"],
    correcta: 1,
  },
  {
    id: "len_seed_4",
    materia: "lenguaje",
    curso: "5basico",
    dificultad: 4,
    tema: "inferencias",
    enunciado:
      "«Ana tomó el paraguas antes de salir.» ¿Qué se puede inferir?",
    opciones: [
      "Ana iba a la playa",
      "Probablemente iba a llover",
      "Ana perdió el paraguas",
      "Era de noche",
    ],
    correcta: 1,
  },
  {
    id: "len_seed_5",
    materia: "lenguaje",
    curso: "5basico",
    dificultad: 5,
    tema: "comprension_lectora",
    enunciado:
      "En una fábula, la tortuga gana la carrera por ser constante. ¿Cuál es la moraleja?",
    opciones: [
      "El más rápido siempre gana",
      "La constancia vence a la rapidez confiada",
      "No hay que competir",
      "Las tortugas son veloces",
    ],
    correcta: 1,
  },

  // ---------------- CIENCIAS ----------------
  {
    id: "cie_seed_1",
    materia: "ciencias",
    curso: "5basico",
    dificultad: 1,
    tema: "seres_vivos",
    enunciado: "¿Qué necesitan las plantas para fabricar su alimento?",
    opciones: ["Luz del sol", "Oscuridad", "Sal", "Ruido"],
    correcta: 0,
  },
  {
    id: "cie_seed_2",
    materia: "ciencias",
    curso: "5basico",
    dificultad: 2,
    tema: "cuerpo_humano",
    enunciado: "¿Qué órgano bombea la sangre por el cuerpo?",
    opciones: ["El pulmón", "El corazón", "El hígado", "El estómago"],
    correcta: 1,
  },
  {
    id: "cie_seed_3",
    materia: "ciencias",
    curso: "5basico",
    dificultad: 3,
    tema: "materia",
    enunciado: "El agua pasa de líquido a gas cuando se calienta. ¿Cómo se llama?",
    opciones: ["Congelación", "Evaporación", "Solidificación", "Filtración"],
    correcta: 1,
  },
  {
    id: "cie_seed_4",
    materia: "ciencias",
    curso: "5basico",
    dificultad: 4,
    tema: "ecosistemas",
    enunciado:
      "En una cadena alimentaria, ¿qué rol cumple una planta?",
    opciones: ["Consumidor", "Productor", "Descomponedor", "Depredador"],
    correcta: 1,
  },
  {
    id: "cie_seed_5",
    materia: "ciencias",
    curso: "5basico",
    dificultad: 5,
    tema: "energia",
    enunciado:
      "Un panel solar convierte la luz del sol en energía…",
    opciones: ["Térmica", "Eléctrica", "Sonora", "Nuclear"],
    correcta: 1,
  },

  // ---------------- HISTORIA ----------------
  {
    id: "his_seed_1",
    materia: "historia",
    curso: "5basico",
    dificultad: 1,
    tema: "geografia_chile",
    enunciado: "¿Cuál océano baña las costas de Chile?",
    opciones: ["Atlántico", "Pacífico", "Índico", "Ártico"],
    correcta: 1,
  },
  {
    id: "his_seed_2",
    materia: "historia",
    curso: "5basico",
    dificultad: 2,
    tema: "pueblos_originarios",
    enunciado: "¿Cuál es un pueblo originario del sur de Chile?",
    opciones: ["Mapuche", "Inca", "Azteca", "Maya"],
    correcta: 0,
  },
  {
    id: "his_seed_3",
    materia: "historia",
    curso: "5basico",
    dificultad: 3,
    tema: "geografia_chile",
    enunciado: "¿Cómo se llama la larga cordillera al este de Chile?",
    opciones: ["Los Andes", "Los Alpes", "El Himalaya", "La Costa"],
    correcta: 0,
  },
  {
    id: "his_seed_4",
    materia: "historia",
    curso: "5basico",
    dificultad: 4,
    tema: "descubrimiento",
    enunciado:
      "¿Quién encabezó la primera expedición española que llegó a Chile por el desierto?",
    opciones: ["Pedro de Valdivia", "Diego de Almagro", "Colón", "Magallanes"],
    correcta: 1,
  },
  {
    id: "his_seed_5",
    materia: "historia",
    curso: "5basico",
    dificultad: 5,
    tema: "institucionalidad",
    enunciado:
      "¿Cuál poder del Estado se encarga de crear las leyes en Chile?",
    opciones: [
      "El Poder Judicial",
      "El Poder Legislativo",
      "El Poder Ejecutivo",
      "Las Fuerzas Armadas",
    ],
    correcta: 1,
  },

  // ---------------- INGLÉS ----------------
  {
    id: "ing_seed_1",
    materia: "ingles",
    curso: "5basico",
    dificultad: 1,
    tema: "vocabulario",
    enunciado: "¿Qué significa la palabra «dog»?",
    opciones: ["Gato", "Perro", "Casa", "Árbol"],
    correcta: 1,
  },
  {
    id: "ing_seed_2",
    materia: "ingles",
    curso: "5basico",
    dificultad: 2,
    tema: "colores",
    enunciado: "¿Cómo se dice «rojo» en inglés?",
    opciones: ["Blue", "Green", "Red", "Yellow"],
    correcta: 2,
  },
  {
    id: "ing_seed_3",
    materia: "ingles",
    curso: "5basico",
    dificultad: 3,
    tema: "gramatica",
    enunciado: "Completa: «She ___ a student.»",
    opciones: ["am", "is", "are", "be"],
    correcta: 1,
  },
  {
    id: "ing_seed_4",
    materia: "ingles",
    curso: "5basico",
    dificultad: 4,
    tema: "comprension",
    enunciado: "«I have two brothers and one sister.» ¿Cuántos hermanos tiene en total?",
    opciones: ["Two", "Three", "One", "Four"],
    correcta: 1,
  },
  {
    id: "ing_seed_5",
    materia: "ingles",
    curso: "5basico",
    dificultad: 5,
    tema: "gramatica",
    enunciado: "Elige la oración correcta en pasado:",
    opciones: [
      "Yesterday I go to school",
      "Yesterday I went to school",
      "Yesterday I going to school",
      "Yesterday I goed to school",
    ],
    correcta: 1,
  },
];
